# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 16:38
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170613_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='thumbs',
            field=models.ImageField(default='image', upload_to=accounts.models.upload_location),
        ),
    ]
